import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/common/header/navbar';
import Footer from '@/components/common/footer/footer';
import SecondNav from '@/components/common/header/secondNav';
import ConditionalNav from '@/components/common/header/conditionalNav';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<ConditionalNav />
				<main className="main-w3rk-content-wrapper">{children}</main>
				<Footer />
			</body>
		</html>
	);
}
